#db:
# image: mysql
# environment:
#  - MYSQL_ROOT_PASSWORD=rootpassword
#  - MYSQL_USER=composetest
#  - MYSQL_PASSWORD=testpassword
#  - MYSQL_DATABASE=composetest
# ports:
#   - "3306:3306"
web:
 restart: always

 build: .

# links:
#  - 'db'
 volumes:
  - '.:/user/src'  # Magic
 ports:
  - '8005:8000'
 environment:
#  - DATABASE_HOST=localhost
  - DATABASE_NAME=composetest
  - DATABASE_USER=composetest
  - DATABASE_PASSWORD=rootpassword

