# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20170415_0731'),
    ]

    operations = [
    ]
